=== humeratasleem-sd/WiproTnp/WebContent/XML/DTD/Problem3/Student.dtd
<!ELEMENT students (student+)>

<!ELEMENT student (name, age, gender, course)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT course (#PCDATA)>

=== humeratasleem-sd/WiproTnp/WebContent/XML/DTD/Problem3/Student.xml
<?xml version="1.0"?>

<!DOCTYPE students SYSTEM "Student.dtd">

<students>

    <student>
        <name>Rahul</name>
        <age>21</age>
        <gender>Male</gender>
        <course>Java</course>
    </student>

    <student>
        <name>Priya</name>
        <age>22</age>
        <gender>Female</gender>
        <course>Python</course>
    </student>

</students>
